// web/src/screens/GroupsScreen.tsx
/* Grupos de afinidad datamined con filtro por puntos y lista expandible.
   Porte de ui/groups/GroupsScreen.kt. */

import { useState } from 'react'
import { useAppStore } from '../state/store'
import { useI18n } from '../i18n'
import { displayName } from '../domain/models'
import { colorDeRango } from '../theme/theme'
import { HeaderBarConVolver } from '../components/HeaderBar'

const OPCIONES = [0, 2, 5, 7, 8]

/* Mismos umbrales de rango que el modelo (par): ◎ ≥20, ○ ≥10, △ ≥4. */
function claseDePuntos(puntos: number): string | null {
  if (puntos >= 20) return 'rank-great'
  if (puntos >= 10) return 'rank-good'
  if (puntos >= 4) return 'rank-fair'
  return null
}

export function GroupsScreen({ onVolver }: { onVolver: () => void }) {
  const { modelo } = useAppStore()
  const { t, japones } = useI18n()
  const [min, setMin] = useState(0)
  const [grupoAbierto, setGrupoAbierto] = useState<number | null>(null)

  if (!modelo) return <div className="centrado">{t('calculando')}</div>

  const grupos = modelo.todosLosGrupos().filter((g) => g.puntos >= min)

  return (
    <div className="pantalla">
      <HeaderBarConVolver titulo={t('tab_groups')} onVolver={onVolver} />

      <div className="chips-filtro" role="group" aria-label={t('filtro_todos')}>
        {OPCIONES.map((valor) => (
          <button
            key={valor}
            type="button"
            className={valor === min ? 'filtro-chip activo' : 'filtro-chip'}
            aria-pressed={valor === min}
            onClick={() => setMin(valor)}
          >
            {valor === 0 ? t('filtro_todos') : t('filtro_pt', valor)}
          </button>
        ))}
      </div>

      {grupos.length === 0 ? (
        <div className="centrado">{t('sin_grupos_filtro')}</div>
      ) : (
        <ul className="lista-grupos">
          {grupos.map((grupo) => {
            const miembros = modelo.miembrosDeGrupo(grupo.tipo)
            const abierto = grupoAbierto === grupo.tipo
            const estadoTxt = abierto ? t('expandido') : t('contraido')
            return (
              <li key={grupo.tipo}>
                <article className={abierto ? 'card grupo abierto' : 'card grupo'}>
                  <button
                    type="button"
                    className="grupo-cabecera"
                    aria-expanded={abierto}
                    aria-describedby={`estado-grupo-${grupo.tipo}`}
                    onClick={() => setGrupoAbierto(abierto ? null : grupo.tipo)}
                  >
                    <span id={`estado-grupo-${grupo.tipo}`} className="oculto-visualmente">
                      {estadoTxt}
                    </span>
                    <span className="grupo-id">#{grupo.tipo}</span>
                    <span className="secundario grupo-cantidad">{t('miembros_cantidad', miembros.length)}</span>
                    <span
                      className="grupo-puntos"
                      style={{ color: colorDeRango(claseDePuntos(grupo.puntos)) ?? 'var(--texto)' }}
                    >
                      {grupo.puntos}pt
                    </span>
                  </button>
                  {abierto ? (
                    <div className="grupo-miembros">
                      {miembros.map((m) => (
                        <span key={m.charId} className="miembro">
                          {displayName(m, japones)}
                        </span>
                      ))}
                    </div>
                  ) : null}
                </article>
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}

// sitio/src/lib/screens/GroupsScreen.svelte
<script lang="ts">
/* Grupos de afinidad datamined con filtro por puntos y lista expandible. */

import { store } from '$lib/state/store.svelte'
import { crearI18n } from '$lib/i18n'
import { displayName } from '$lib/domain/models'
import { colorDeRango } from '$lib/theme/theme'
import HeaderBar from '$lib/components/HeaderBar.svelte'

interface Props {
  onVolver: () => void
}

let { onVolver }: Props = $props()
const i18n = $derived(crearI18n(store.idioma))

const OPCIONES = [0, 2, 5, 7, 8]
let min = $state(0)
let grupoAbierto = $state<number | null>(null)

const grupos = $derived(store.modelo === null ? [] : store.modelo.todosLosGrupos().filter((g) => g.puntos >= min))

function claseDePuntos(puntos: number): string | null {
  if (puntos >= 20) return 'rank-great'
  if (puntos >= 10) return 'rank-good'
  if (puntos >= 4) return 'rank-fair'
  return null
}
</script>

<svelte:head>
  <title>{i18n.t('tab_groups')} · Uma Afinidad</title>
</svelte:head>

{#if store.modelo === null}
  <div class="centrado">{i18n.t('calculando')}</div>
{:else}
  <div class="pantalla">
    <HeaderBar titulo={i18n.t('tab_groups')} {onVolver} />

    <div class="chips-filtro" role="group" aria-label={i18n.t('filtro_todos')}>
      {#each OPCIONES as valor (valor)}
        <button
          type="button"
          class={valor === min ? 'filtro-chip activo' : 'filtro-chip'}
          aria-pressed={valor === min}
          onclick={() => (min = valor)}
        >
          {valor === 0 ? i18n.t('filtro_todos') : i18n.t('filtro_pt', valor)}
        </button>
      {/each}
    </div>

    {#if grupos.length === 0}
      <div class="centrado">{i18n.t('sin_grupos_filtro')}</div>
    {:else}
      <ul class="lista-grupos">
        {#each grupos as grupo (grupo.tipo)}
          {@const miembros = store.modelo.miembrosDeGrupo(grupo.tipo)}
          {@const abierto = grupoAbierto === grupo.tipo}
          <li>
            <article class={abierto ? 'card grupo abierto' : 'card grupo'}>
              <button
                type="button"
                class="grupo-cabecera"
                aria-expanded={abierto}
                aria-describedby={`estado-grupo-${grupo.tipo}`}
                onclick={() => (grupoAbierto = abierto ? null : grupo.tipo)}
              >
                <span id={`estado-grupo-${grupo.tipo}`} class="oculto-visualmente">
                  {i18n.t(abierto ? 'expandido' : 'contraido')}
                </span>
                <span class="grupo-id">#{grupo.tipo}</span>
                <span class="secundario grupo-cantidad">
                  {i18n.t('miembros_cantidad', miembros.length)}
                </span>
                <span
                  class="grupo-puntos"
                  style="color:{colorDeRango(claseDePuntos(grupo.puntos)) ?? 'var(--texto)'}"
                >
                  {grupo.puntos}pt
                </span>
              </button>
              {#if abierto}
                <div class="grupo-miembros">
                  {#each miembros as m (m.charId)}
                    <span class="miembro">{displayName(m, i18n.japones)}</span>
                  {/each}
                </div>
              {/if}
            </article>
          </li>
        {/each}
      </ul>
    {/if}
  </div>
{/if}
