// web/src/screens/RankingScreen.tsx
/* Ranking con dos modos: "Umas más versátiles" (total afinidad) y
   "Mejores padres" (veces como padre óptimo + % + media). Porte de
   ui/ranking/RankingScreen.kt. */

import { useEffect, useState } from 'react'
import type { RankingAfinidad, RankingPadre } from '../domain/affinity'
import { useAppStore } from '../state/store'
import { useI18n } from '../i18n'
import { displayName } from '../domain/models'
import { pedirRankingAfinidad, pedirRankingPadres } from '../worker/cliente'
import { HeaderBarConVolver } from '../components/HeaderBar'
import { RankPill } from '../components/RankPill'
import { Medalla } from '../components/Medalla'
import { Avatar } from '../components/Avatar'
import { Dialogo } from '../components/Modal'
import { IconInfo } from '../components/Icons'
import { colorDeMedalla } from '../theme/theme'

export type ModoRanking = 'VERSATIL' | 'PADRES'

export function RankingScreen({ onVolver, modoInicial = 'VERSATIL' }: { onVolver: () => void; modoInicial?: ModoRanking }) {
  const { modelo } = useAppStore()
  const { t } = useI18n()
  const [modo, setModo] = useState<ModoRanking>(modoInicial)
  const [mostrarAyuda, setMostrarAyuda] = useState(false)
  const [ranking, setRanking] = useState<RankingAfinidad[] | null>(null)
  const [rankingPadres, setRankingPadres] = useState<RankingPadre[] | null>(null)

  useEffect(() => {
    if (!modelo) return
    let activo = true
    void Promise.all([pedirRankingAfinidad(), pedirRankingPadres()]).then(([a, p]) => {
      if (!activo) return
      setRanking(a)
      setRankingPadres(p)
    })
    return () => {
      activo = false
    }
  }, [modelo])

  if (!modelo) return <div className="centrado">{t('calculando')}</div>

  return (
    <div className="pantalla">
      <HeaderBarConVolver titulo={t('tab_ranking')} onVolver={onVolver} />

      <div className="segmentado" role="group" aria-label={t('tab_ranking')}>
        <button
          type="button"
          className={modo === 'VERSATIL' ? 'segmento activo' : 'segmento'}
          aria-pressed={modo === 'VERSATIL'}
          onClick={() => setModo('VERSATIL')}
        >
          {t('ranking_modo_versatil')}
        </button>
        <button
          type="button"
          className={modo === 'PADRES' ? 'segmento activo' : 'segmento'}
          aria-pressed={modo === 'PADRES'}
          onClick={() => setModo('PADRES')}
        >
          {t('ranking_modo_padres')}
        </button>
      </div>

      {modo === 'VERSATIL' ? (
        ranking === null ? (
          <div className="centrado">{t('calculando')}</div>
        ) : ranking.length === 0 ? (
          <div className="centrado">{t('sin_datos')}</div>
        ) : (
          <ul className="lista-ranking">
            {ranking.map((entry, i) => (
              <li key={entry.personaje.charId}>
                <CardFilaRanking pos={i} entry={entry} modelo={modelo} />
              </li>
            ))}
          </ul>
        )
      ) : (
        <>
          <button
            type="button"
            className="ayuda-ranking"
            onClick={() => setMostrarAyuda(true)}
            aria-label={t('ranking_padres_ayuda_titulo')}
          >
            <span className="secundario">{t('ranking_padres_ayuda_corta')}</span>
            <IconInfo className="icono-info" />
          </button>
          {rankingPadres === null ? (
            <div className="centrado">{t('calculando')}</div>
          ) : rankingPadres.length === 0 ? (
            <div className="centrado">{t('sin_datos')}</div>
          ) : (
            <ul className="lista-ranking">
              {rankingPadres.map((entry, i) => (
                <li key={entry.personaje.charId}>
                  <CardFilaPadre pos={i} entry={entry} />
                </li>
              ))}
            </ul>
          )}
        </>
      )}

      <Dialogo
        open={mostrarAyuda}
        titulo={t('ranking_padres_ayuda_titulo')}
        descripcion={t('ranking_padres_ayuda_larga')}
        onClose={() => setMostrarAyuda(false)}
      >
        <button type="button" className="boton-texto" onClick={() => setMostrarAyuda(false)}>
          {t('entendido')}
        </button>
      </Dialogo>
    </div>
  )
}

function estiloTop(pos: number): React.CSSProperties {
  if (pos >= 3) return {}
  const color = colorDeMedalla(pos)
  return {
    background: 'color-mix(in srgb, var(--contenedor-primario) 25%, transparent)',
    borderColor: color ? `color-mix(in srgb, ${color} 60%, transparent)` : undefined,
  }
}

function CardFilaRanking({ pos, entry, modelo }: { pos: number; entry: RankingAfinidad; modelo: import('../domain/affinity').AffinityModel }) {
  const { japones } = useI18n()
  const nombre = displayName(entry.personaje, japones)
  return (
    <article className="card fila-ranking" style={estiloTop(pos)}>
      <Medalla pos={pos} />
      <Avatar id={entry.personaje.charId} nombre={nombre} tamano={36} />
      <span className="fila-ranking-nombre">{nombre}</span>
      <RankPill rango={modelo.rangoRanking(entry.total)} puntos={entry.total} />
    </article>
  )
}

function CardFilaPadre({ pos, entry }: { pos: number; entry: RankingPadre }) {
  const { t, japones } = useI18n()
  const nombre = displayName(entry.personaje, japones)
  return (
    <article className="card fila-ranking" style={estiloTop(pos)}>
      <Medalla pos={pos} />
      <Avatar id={entry.personaje.charId} nombre={nombre} tamano={36} />
      <span className="fila-ranking-texto">
        <span className="fila-ranking-nombre">{nombre}</span>
        <span className="secundario fila-ranking-media">{t('ranking_padres_media', entry.puntosMedios)}</span>
      </span>
      <span className="fila-ranking-veces">{t('ranking_padres_veces', entry.veces, Math.trunc(entry.porcentaje))}</span>
    </article>
  )
}

// sitio/src/lib/screens/RankingScreen.svelte
<script lang="ts">
/* Ranking con dos modos: "Umas más versátiles" (total afinidad) y
   "Mejores padres" (veces como padre óptimo + % + media). */

import type { RankingAfinidad, RankingPadre } from '$lib/domain/affinity'
import { store } from '$lib/state/store.svelte'
import { crearI18n } from '$lib/i18n'
import { displayName } from '$lib/domain/models'
import { pedirRankingAfinidad, pedirRankingPadres } from '$lib/worker/cliente'
import { Async } from '$lib/state/async.svelte'
import HeaderBar from '$lib/components/HeaderBar.svelte'
import RankPill from '$lib/components/RankPill.svelte'
import Medalla from '$lib/components/Medalla.svelte'
import Avatar from '$lib/components/Avatar.svelte'
import Dialogo from '$lib/components/Dialogo.svelte'
import Icono from '$lib/components/Icono.svelte'
import { colorDeMedalla } from '$lib/theme/theme'

export type ModoRanking = 'VERSATIL' | 'PADRES'

interface Props {
  onVolver: () => void
  modoInicial?: ModoRanking
}

let { onVolver, modoInicial = 'VERSATIL' }: Props = $props()
const i18n = $derived(crearI18n(store.idioma))

// svelte-ignore state_referenced_locally
let modo = $state<ModoRanking>(modoInicial)
let mostrarAyuda = $state(false)
const versatil = new Async(() => pedirRankingAfinidad())
const padres = new Async(() => pedirRankingPadres())

$effect(() => {
  if (store.modelo !== null) {
    void versatil.ejecutar()
    void padres.ejecutar()
  }
})

function estiloTop(pos: number): string {
  if (pos >= 3) return ''
  const color = colorDeMedalla(pos)
  return `background:color-mix(in srgb, var(--contenedor-primario) 55%, transparent);border-color:${
    color ? `color-mix(in srgb, ${color} 60%, transparent)` : 'var(--contorno-variante)'
  }`
}
</script>

<svelte:head>
  <title>{i18n.t('tab_ranking')} · Uma Afinidad</title>
</svelte:head>

{#if store.modelo === null}
  <div class="centrado">{i18n.t('calculando')}</div>
{:else}
  <div class="pantalla">
    <HeaderBar titulo={i18n.t('tab_ranking')} {onVolver} />

    <div class="segmentado" role="group" aria-label={i18n.t('tab_ranking')}>
      <button
        type="button"
        class={modo === 'VERSATIL' ? 'segmento activo' : 'segmento'}
        aria-pressed={modo === 'VERSATIL'}
        onclick={() => (modo = 'VERSATIL')}
      >
        {i18n.t('ranking_modo_versatil')}
      </button>
      <button
        type="button"
        class={modo === 'PADRES' ? 'segmento activo' : 'segmento'}
        aria-pressed={modo === 'PADRES'}
        onclick={() => (modo = 'PADRES')}
      >
        {i18n.t('ranking_modo_padres')}
      </button>
    </div>

    {#if modo === 'VERSATIL'}
      {#if versatil.datos === null}
        <div class="centrado">{i18n.t('calculando')}</div>
      {:else if versatil.datos.length === 0}
        <div class="centrado">{i18n.t('sin_datos')}</div>
      {:else}
        <ul class="lista-ranking">
          {#each versatil.datos as entry, i (entry.personaje.charId)}
            <li>
              {@render filaVersatil(entry, i, store.modelo)}
            </li>
          {/each}
        </ul>
      {/if}
    {:else}
      <button
        type="button"
        class="ayuda-ranking"
        onclick={() => (mostrarAyuda = true)}
        aria-label={i18n.t('ranking_padres_ayuda_titulo')}
      >
        <span class="secundario">{i18n.t('ranking_padres_ayuda_corta')}</span>
        <Icono nombre="info" class="icono-info" />
      </button>
      {#if padres.datos === null}
        <div class="centrado">{i18n.t('calculando')}</div>
      {:else if padres.datos.length === 0}
        <div class="centrado">{i18n.t('sin_datos')}</div>
      {:else}
        <ul class="lista-ranking">
          {#each padres.datos as entry, i (entry.personaje.charId)}
            <li>
              {@render filaPadre(entry, i)}
            </li>
          {/each}
        </ul>
      {/if}
    {/if}

    <Dialogo
      open={mostrarAyuda}
      titulo={i18n.t('ranking_padres_ayuda_titulo')}
      descripcion={i18n.t('ranking_padres_ayuda_larga')}
      onClose={() => (mostrarAyuda = false)}
    >
      <button type="button" class="boton-texto" onclick={() => (mostrarAyuda = false)}>
        {i18n.t('entendido')}
      </button>
    </Dialogo>
  </div>
{/if}

{#snippet filaVersatil(entry: RankingAfinidad, pos: number, modelo: import('$lib/domain/affinity').AffinityModel)}
  {@const nombre = displayName(entry.personaje, i18n.japones)}
  <article class="card fila-ranking" style={estiloTop(pos)}>
    <Medalla {pos} />
    <Avatar id={entry.personaje.charId} nombre={nombre} tamano={36} />
    <span class="fila-ranking-nombre">{nombre}</span>
    <RankPill rango={modelo.rangoRanking(entry.total)} puntos={entry.total} />
  </article>
{/snippet}

{#snippet filaPadre(entry: RankingPadre, pos: number)}
  {@const nombre = displayName(entry.personaje, i18n.japones)}
  <article class="card fila-ranking" style={estiloTop(pos)}>
    <Medalla {pos} />
    <Avatar id={entry.personaje.charId} nombre={nombre} tamano={36} />
    <span class="fila-ranking-texto">
      <span class="fila-ranking-nombre">{nombre}</span>
      <span class="secundario fila-ranking-media">
        {i18n.t('ranking_padres_media', entry.puntosMedios)}
      </span>
    </span>
    <span class="fila-ranking-veces">
      {i18n.t('ranking_padres_veces', entry.veces, Math.trunc(entry.porcentaje))}
    </span>
  </article>
{/snippet}
