// web/src/components/HeaderBar.tsx
/* Cabeceras uniformes (altura fija) para tabs y pantallas de Más.
   Espejo de ui/componentes/Componentes.kt (HeaderBar y
   HeaderBarConVolver) con semántica de encabezado. */

import type { ReactNode } from 'react'
import { IconAtras } from './Icons'
import { useI18n } from '../i18n'

interface HeaderBarProps {
  titulo: string
  pillTexto?: string
  chip?: ReactNode
}

export function HeaderBar({ titulo, pillTexto, chip }: HeaderBarProps) {
  return (
    <header className="header-bar">
      <h1>{titulo}</h1>
      {chip}
      {pillTexto ? <span className="header-pill">{pillTexto}</span> : null}
    </header>
  )
}

interface HeaderBarConVolverProps extends HeaderBarProps {
  onVolver: () => void
}

export function HeaderBarConVolver({ titulo, onVolver, pillTexto }: HeaderBarConVolverProps) {
  const { t } = useI18n()
  return (
    <header className="header-bar" style={{ paddingLeft: '0.25rem' }}>
      <button type="button" className="icon-button" onClick={onVolver} aria-label={t('volver')}>
        <IconAtras />
      </button>
      <h1>{titulo}</h1>
      {pillTexto ? <span className="header-pill">{pillTexto}</span> : null}
    </header>
  )
}

// sitio/src/lib/components/HeaderBar.svelte
<script lang="ts">
/* Cabecera uniforme de página. Con `onVolver` agrega el botón atrás. */

import type { Snippet } from 'svelte'
import { store } from '../state/store.svelte'
import { crearI18n } from '../i18n'
import Icono from './Icono.svelte'

interface Props {
  titulo: string
  pillTexto?: string
  chip?: Snippet
  onVolver?: () => void
}

let { titulo, pillTexto, chip, onVolver }: Props = $props()
const i18n = $derived(crearI18n(store.idioma))
</script>

<header class="header-bar">
  {#if onVolver}
    <button type="button" class="icon-button" onclick={onVolver} aria-label={i18n.t('volver')}>
      <Icono nombre="atras" />
    </button>
  {/if}
  <h1>{titulo}</h1>
  {#if chip}{@render chip()}{/if}
  {#if pillTexto}<span class="header-pill">{pillTexto}</span>{/if}
</header>
