// sitio/src/lib/screens/CompatScreen.svelte
<script lang="ts">
/* Herencia (compatibilidad): slots de la genealogía, buscador difuso,
   grilla de personajes y panel de resultado. */

import type { Character } from '$lib/domain/models'
import { displayName } from '$lib/domain/models'
import { coincideDifuso, rankearSugerencias } from '$lib/domain/busqueda'
import { ModoGrilla } from '$lib/data/prefs'
import { store } from '$lib/state/store.svelte'
import { QuitarResultado, ToggleResultado } from '$lib/state/resultado'
import { crearI18n } from '$lib/i18n'
import { enlaceSeleccion, PARAM_SELECCION } from '$lib/state/compartir'
import { page } from '$app/state'
import { colorDeAvatar, colorDeGenealogia } from '$lib/theme/theme'
import Avatar from '$lib/components/Avatar.svelte'
import HeaderBar from '$lib/components/HeaderBar.svelte'
import BottomSheet from '$lib/components/BottomSheet.svelte'
import Dialogo from '$lib/components/Dialogo.svelte'
import { useSnackbar } from '$lib/components/snackbar'
import ResultadoPanel from '$lib/components/ResultadoPanel.svelte'
import Icono from '$lib/components/Icono.svelte'

const ETIQUETAS_ROL = [
  'rol_hijo',
  'rol_padre1',
  'rol_padre2',
  'rol_abuelo1_p1',
  'rol_abuelo2_p1',
  'rol_abuelo1_p2',
  'rol_abuelo2_p2',
]

const i18n = $derived(crearI18n(store.idioma))
const { avisar } = useSnackbar()

let filtro = $state('')
let sheetAbierto = $state(false)
let dialogoQuitar = $state(false)
let sugerenciaActiva = $state(-1)

const sugerencias = $derived(
  store.modelo && filtro.trim().length >= 2 ? rankearSugerencias(store.modelo.personajes, filtro) : [],
)
const seleccionSet = $derived(new Set(store.seleccion.filter((v): v is number => v !== null)))
const filtrados = $derived.by(() => {
  if (!store.modelo) return []
  return store.modelo.personajes
    .filter((c) => c.playable === true && c.active === true)
    .filter((c) => coincideDifuso(c, filtro))
    .map((c, i) => ({ c, i }))
    .sort((a, b) => {
      const ra = seleccionSet.has(a.c.charId) ? 0 : 1
      const rb = seleccionSet.has(b.c.charId) ? 0 : 1
      return ra - rb || a.i - b.i
    })
    .map((x) => x.c)
})
const seleccionados = $derived(store.seleccion.filter((v) => v !== null).length)

/* Selección recibida por URL (?s=...): se aplica una sola vez, cuando el
   modelo ya está listo para validar los ids. */
let compartidoAplicado = $state(false)
$effect(() => {
  if (store.modelo === null || compartidoAplicado) return
  compartidoAplicado = true
  const raw = page.url.searchParams.get(PARAM_SELECCION)
  if (raw !== null && !store.aplicarSeleccionCompartida(raw)) {
    avisar(i18n.t('enlace_invalido'))
  }
})

async function compartir(): Promise<void> {
  if (seleccionados === 0) return
  const url = enlaceSeleccion(window.location.pathname, store.seleccion)
  if (typeof navigator.share === 'function') {
    try {
      await navigator.share({ title: 'Uma Afinidad', url })
    } catch {
      /* el usuario canceló la hoja de compartir */
    }
    return
  }
  try {
    await navigator.clipboard.writeText(url)
    avisar(i18n.t('enlace_copiado'))
  } catch {
    avisar(i18n.t('enlace_invalido'))
  }
}

function posicionesRol(id: number): number[] {
  const out: number[] = []
  store.seleccion.forEach((v, i) => {
    if (v === id) out.push(i)
  })
  return out
}

function rolCorto(i: number): string {
  if (i === 0) return 'rol_corto_hijo'
  if (i <= 2) return 'rol_corto_padre'
  return 'rol_corto_abuelo'
}

function elegirSugerencia(id: number): void {
  const r = store.toggle(id)
  if (r === ToggleResultado.COLOCADO || r === ToggleResultado.QUITADO) {
    filtro = ''
    sugerenciaActiva = -1
  }
}

function manejarToggle(id: number): void {
  const r = store.toggle(id)
  if (r === ToggleResultado.SELECCION_COMPLETA) avisar(i18n.t('seleccion_completa'))
  else if (r === ToggleResultado.REGLA) avisar(i18n.t('regla_slots'))
}

function manejarQuitar(i: number): void {
  if (store.quitarSlot(i) === QuitarResultado.NECESITA_CONFIRMACION) {
    dialogoQuitar = true
  }
}

function onBuscarKeyDown(evento: KeyboardEvent): void {
  if (sugerencias.length === 0) return
  if (evento.key === 'ArrowDown') {
    evento.preventDefault()
    sugerenciaActiva = Math.min(sugerenciaActiva + 1, sugerencias.length - 1)
  } else if (evento.key === 'ArrowUp') {
    evento.preventDefault()
    sugerenciaActiva = Math.max(sugerenciaActiva - 1, 0)
  } else if (evento.key === 'Enter' && sugerenciaActiva >= 0) {
    evento.preventDefault()
    elegirSugerencia(sugerencias[sugerenciaActiva].charId)
  } else if (evento.key === 'Escape') {
    sugerenciaActiva = -1
  }
}
</script>

<svelte:head>
  <title>{i18n.t('seccion_herencia')} · Uma Afinidad</title>
</svelte:head>

{#if store.modelo === null}
  <div class="centrado">{i18n.t('calculando')}</div>
{:else}
  <div class="pantalla compat">
    <HeaderBar
      titulo={i18n.t('seccion_herencia')}
      pillTexto={i18n.t('herencia_contador', seleccionados)}
    />

    <div class="slots">
      <div class="slots-fila">
        {#each [0, 1, 2] as slot (slot)}
          {@render slotChip(slot)}
        {/each}
      </div>
      <div class="slots-fila">
        {#each [3, 4, 5, 6] as slot (slot)}
          {@render slotChip(slot)}
        {/each}
      </div>
    </div>

    <div class="buscador">
      <div class="buscador-campo">
        <Icono nombre="buscar" class="buscador-icono" />
        <input
          type="search"
          role="combobox"
          aria-expanded={sugerencias.length > 0}
          aria-controls="sugerencias-lista"
          aria-autocomplete="list"
          placeholder={i18n.t('buscar')}
          bind:value={filtro}
          oninput={() => (sugerenciaActiva = -1)}
          onkeydown={onBuscarKeyDown}
        />
        {#if filtro !== ''}
          <button
            type="button"
            class="icon-button"
            onclick={() => (filtro = '')}
            aria-label={i18n.t('limpiar_todo')}
          >
            <Icono nombre="cerrar" />
          </button>
        {/if}
      </div>

      {#if sugerencias.length > 0}
        <ul id="sugerencias-lista" role="listbox" class="sugerencias">
          {#each sugerencias as c, indice (c.charId)}
            {@const principal = displayName(c, i18n.japones)}
            {@const secundario = i18n.japones ? (c.enName ?? '') : (c.jpName ?? '')}
            <li role="option" aria-selected={indice === sugerenciaActiva}>
              <button
                type="button"
                class={indice === sugerenciaActiva ? 'sugerencia activa' : 'sugerencia'}
                onclick={() => elegirSugerencia(c.charId)}
                onmouseenter={() => (sugerenciaActiva = indice)}
              >
                <Avatar id={c.charId} nombre={principal} tamano={32} />
                <span class="sugerencia-texto">
                  <span class="sugerencia-principal">{principal}</span>
                  {#if secundario !== ''}
                    <span class="sugerencia-secundaria">{secundario}</span>
                  {/if}
                </span>
              </button>
            </li>
          {/each}
        </ul>
      {/if}
    </div>

    {#if filtrados.length === 0}
      <div class="centrado">
        <div>
          <Icono nombre="buscar" />
          <p>{i18n.t('sin_resultados')}</p>
        </div>
      </div>
    {:else if store.modoGrilla === ModoGrilla.TARJETAS}
      <ul class="grilla-tarjetas">
        {#each filtrados as c (c.charId)}
          {@render tarjeta(c)}
        {/each}
      </ul>
    {:else}
      <ul class="grilla-lista">
        {#each filtrados as c (c.charId)}
          {@render fila(c)}
        {/each}
      </ul>
    {/if}

    {#if seleccionados > 0}
      <button type="button" class="fab secundario" onclick={() => void compartir()}>
        {i18n.t('compartir')}
      </button>
      <button type="button" class="fab" aria-live="polite" onclick={() => (sheetAbierto = true)}>
        <Icono nombre="corazon" />
        {i18n.t('ver_afinidad')}
      </button>
    {/if}

    <BottomSheet
      open={sheetAbierto && store.resultado !== null}
      onClose={() => (sheetAbierto = false)}
      labelledBy="resultado-titulo"
    >
      {#if store.resultado !== null}
        <ResultadoPanel modelo={store.modelo} res={store.resultado} japones={i18n.japones} />
      {/if}
    </BottomSheet>

    <Dialogo
      open={dialogoQuitar}
      titulo={i18n.t('quitar_hijo_titulo')}
      onClose={() => (dialogoQuitar = false)}
    >
      <button
        type="button"
        class="boton-texto"
        onclick={() => {
          store.confirmarQuitarSoloHijo()
          dialogoQuitar = false
        }}
      >
        {i18n.t('quitar_solo_hijo')}
      </button>
      <button
        type="button"
        class="boton-texto"
        onclick={() => {
          store.limpiarTodo()
          dialogoQuitar = false
        }}
      >
        {i18n.t('limpiar_todo')}
      </button>
    </Dialogo>
  </div>
{/if}

{#snippet slotChip(slot: number)}
  {@const id = store.seleccion[slot]}
  {@const personaje = id !== null && store.modelo ? store.modelo.porId(id) : null}
  {@const rolColor = colorDeGenealogia(slot)}
  {@const borde = personaje
    ? `color-mix(in srgb, ${rolColor} 70%, transparent)`
    : 'var(--contorno-variante)'}
  {#if personaje && id !== null}
    <button
      type="button"
      class="slot-chip"
      style="border-color:{borde}"
      onclick={() => manejarQuitar(slot)}
      aria-label={`${i18n.t(ETIQUETAS_ROL[slot])}: ${displayName(
        personaje,
        i18n.japones,
      )}. ${i18n.t('quitar_personaje')}`}
    >
      <span class="slot-etiqueta" style="color:{rolColor}">{i18n.t(ETIQUETAS_ROL[slot])}</span>
      <span class="slot-nombre seleccionado">{displayName(personaje, i18n.japones)}</span>
    </button>
  {:else}
    <div class="slot-chip vacio" style="border-color:{borde}">
      <span class="slot-etiqueta" style="color:{rolColor}">{i18n.t(ETIQUETAS_ROL[slot])}</span>
      <span class="slot-nombre">—</span>
    </div>
  {/if}
{/snippet}

{#snippet tarjeta(personaje: Character)}
  {@const principal = displayName(personaje, i18n.japones)}
  {@const secundario = i18n.japones ? (personaje.enName ?? '') : (personaje.jpName ?? '')}
  {@const roles = posicionesRol(personaje.charId)}
  {@const seleccionado = roles.length > 0}
  {@const rolesTexto = roles.map((r) => i18n.t(rolCorto(r))).join(', ')}
  <li>
    <button
      type="button"
      role="checkbox"
      aria-checked={seleccionado}
      aria-describedby={rolesTexto !== '' ? `roles-${personaje.charId}` : undefined}
      class={seleccionado ? 'card-tarjeta seleccionada' : 'card-tarjeta'}
      onclick={() => manejarToggle(personaje.charId)}
    >
      {#if rolesTexto !== ''}
        <span id={`roles-${personaje.charId}`} class="oculto-visualmente">{rolesTexto}</span>
      {/if}
      <span class="avatar-envoltura">
        <Avatar id={personaje.charId} nombre={principal} tamano={64} />
        {#if seleccionado}
          <span class="check" aria-hidden="true">✓</span>
        {/if}
      </span>
      <span class="nombre-principal">{principal}</span>
      {#if secundario !== ''}
        <span class="nombre-secundario">{secundario}</span>
      {/if}
      {#if roles.length > 0}
        <span class="roles-flow">
          {#each roles as r (r)}
            <span class="rol-tag">{i18n.t(rolCorto(r))}</span>
          {/each}
        </span>
      {/if}
    </button>
  </li>
{/snippet}

{#snippet fila(personaje: Character)}
  {@const principal = displayName(personaje, i18n.japones)}
  {@const secundario = i18n.japones ? (personaje.enName ?? '') : (personaje.jpName ?? '')}
  {@const roles = posicionesRol(personaje.charId)}
  {@const seleccionado = roles.length > 0}
  {@const rolesTexto = roles.map((r) => i18n.t(rolCorto(r))).join(', ')}
  <li>
    <button
      type="button"
      role="checkbox"
      aria-checked={seleccionado}
      aria-describedby={rolesTexto !== '' ? `roles-${personaje.charId}` : undefined}
      class={seleccionado ? 'card-fila seleccionada' : 'card-fila'}
      onclick={() => manejarToggle(personaje.charId)}
    >
      {#if rolesTexto !== ''}
        <span id={`roles-${personaje.charId}`} class="oculto-visualmente">{rolesTexto}</span>
      {/if}
      <span
        class="franja"
        style="background:{colorDeAvatar(personaje.charId)}"
        aria-hidden="true"
      ></span>
      <Avatar id={personaje.charId} nombre={principal} tamano={48} />
      <span class="card-fila-texto">
        <span class="nombre-principal">{principal}</span>
        {#if secundario !== ''}
          <span class="nombre-secundario">{secundario}</span>
        {/if}
      </span>
      {#if seleccionado}
        <span class="roles-flow">
          {#each roles as r (r)}
            <span class="rol-tag">{i18n.t(rolCorto(r))}</span>
          {/each}
          <span class="check-texto" aria-hidden="true">✓</span>
        </span>
      {/if}
    </button>
  </li>
{/snippet}

// web/src/screens/CompatScreen.tsx
/* Pantalla Herencia (compatibilidad). Porte de ui/compat/CompatScreen.kt:
   slots de la genealogía, buscador difuso, grilla de personajes y panel
   de resultado. */

import { useMemo, useState } from 'react'
import type { Character } from '../domain/models'
import { displayName } from '../domain/models'
import { coincideDifuso, rankearSugerencias } from '../domain/busqueda'
import { ModoGrilla } from '../data/prefs'
import { useAppStore, store } from '../state/store'
import { QuitarResultado, ToggleResultado } from '../state/resultado'
import { useI18n } from '../i18n'
import { colorDeAvatar, colorDeGenealogia } from '../theme/theme'
import { Avatar } from '../components/Avatar'
import { HeaderBar } from '../components/HeaderBar'
import { BottomSheet, Dialogo } from '../components/Modal'
import { useSnackbar } from '../components/snackbar'
import { ResultadoPanel } from '../components/ResultadoPanel'
import { IconBuscar, IconCerrar, IconCorazon } from '../components/Icons'

const ETIQUETAS_ROL = [
  'rol_hijo',
  'rol_padre1',
  'rol_padre2',
  'rol_abuelo1_p1',
  'rol_abuelo2_p1',
  'rol_abuelo1_p2',
  'rol_abuelo2_p2',
]

function etiquetaRol(i: number): string {
  return ETIQUETAS_ROL[i]
}

function rolCorto(i: number): string {
  if (i === 0) return 'rol_corto_hijo'
  if (i <= 2) return 'rol_corto_padre'
  return 'rol_corto_abuelo'
}

function posicionesRol(seleccion: (number | null)[], id: number): number[] {
  const out: number[] = []
  seleccion.forEach((v, i) => {
    if (v === id) out.push(i)
  })
  return out
}

export function CompatScreen() {
  const { modelo, seleccion, resultado, modoGrilla } = useAppStore()
  const { avisar } = useSnackbar()
  const { t, japones } = useI18n()
  const [filtro, setFiltro] = useState('')
  const [sheetAbierto, setSheetAbierto] = useState(false)
  const [dialogoQuitar, setDialogoQuitar] = useState(false)
  const [sugerenciaActiva, setSugerenciaActiva] = useState(-1)

  const sugerencias = useMemo(
    () => (modelo && filtro.trim().length >= 2 ? rankearSugerencias(modelo.personajes, filtro) : []),
    [modelo, filtro],
  )

  const seleccionSet = useMemo(() => new Set(seleccion.filter((v): v is number => v !== null)), [seleccion])

  const filtrados = useMemo(() => {
    if (!modelo) return []
    return modelo.personajes
      .filter((c) => c.playable === true && c.active === true)
      .filter((c) => coincideDifuso(c, filtro))
      .map((c, i) => ({ c, i }))
      .sort((a, b) => {
        const ra = seleccionSet.has(a.c.charId) ? 0 : 1
        const rb = seleccionSet.has(b.c.charId) ? 0 : 1
        return ra - rb || a.i - b.i
      })
      .map((x) => x.c)
  }, [modelo, filtro, seleccionSet])

  if (!modelo) {
    return <div className="centrado">{t('calculando')}</div>
  }

  const seleccionados = seleccion.filter((v) => v !== null).length

  function elegirSugerencia(id: number) {
    const r = store.toggle(id)
    if (r === ToggleResultado.COLOCADO || r === ToggleResultado.QUITADO) {
      setFiltro('')
      setSugerenciaActiva(-1)
    }
  }

  function manejarToggle(id: number) {
    const r = store.toggle(id)
    if (r === ToggleResultado.SELECCION_COMPLETA) avisar(t('seleccion_completa'))
    else if (r === ToggleResultado.REGLA) avisar(t('regla_slots'))
  }

  function manejarQuitar(i: number) {
    if (store.quitarSlot(i) === QuitarResultado.NECESITA_CONFIRMACION) {
      setDialogoQuitar(true)
    }
  }

  function onBuscarKeyDown(evento: React.KeyboardEvent<HTMLInputElement>) {
    if (sugerencias.length === 0) return
    if (evento.key === 'ArrowDown') {
      evento.preventDefault()
      setSugerenciaActiva((i) => Math.min(i + 1, sugerencias.length - 1))
    } else if (evento.key === 'ArrowUp') {
      evento.preventDefault()
      setSugerenciaActiva((i) => Math.max(i - 1, 0))
    } else if (evento.key === 'Enter' && sugerenciaActiva >= 0) {
      evento.preventDefault()
      elegirSugerencia(sugerencias[sugerenciaActiva].charId)
    } else if (evento.key === 'Escape') {
      setSugerenciaActiva(-1)
    }
  }

  return (
    <div className="pantalla compat">
      <HeaderBar
        titulo={t('seccion_herencia')}
        pillTexto={t('herencia_contador', seleccionados)}
      />

      {/* Slots de la genealogía, siempre visibles */}
      <div className="slots">
        <div className="slots-fila">
          {[0, 1, 2].map((i) => (
            <SlotChip key={i} slot={i} onQuitar={manejarQuitar} />
          ))}
        </div>
        <div className="slots-fila">
          {[3, 4, 5, 6].map((i) => (
            <SlotChip key={i} slot={i} onQuitar={manejarQuitar} />
          ))}
        </div>
      </div>

      {/* Buscador con autocompletado difuso */}
      <div className="buscador">
        <div className="buscador-campo">
          <IconBuscar className="buscador-icono" />
          <input
            type="search"
            role="combobox"
            aria-expanded={sugerencias.length > 0}
            aria-controls="sugerencias-lista"
            aria-autocomplete="list"
            placeholder={t('buscar')}
            value={filtro}
            onChange={(evento) => {
              setFiltro(evento.target.value)
              setSugerenciaActiva(-1)
            }}
            onKeyDown={onBuscarKeyDown}
          />
          {filtro !== '' ? (
            <button type="button" className="icon-button" onClick={() => setFiltro('')} aria-label={t('limpiar_todo')}>
              <IconCerrar />
            </button>
          ) : null}
        </div>

        {sugerencias.length > 0 ? (
          <ul id="sugerencias-lista" role="listbox" className="sugerencias">
            {sugerencias.map((c, indice) => {
              const principal = displayName(c, japones)
              const secundario = japones ? c.enName ?? '' : c.jpName ?? ''
              return (
                <li key={c.charId} role="option" aria-selected={indice === sugerenciaActiva}>
                  <button
                    type="button"
                    className={indice === sugerenciaActiva ? 'sugerencia activa' : 'sugerencia'}
                    onClick={() => elegirSugerencia(c.charId)}
                    onMouseEnter={() => setSugerenciaActiva(indice)}
                  >
                    <Avatar id={c.charId} nombre={principal} tamano={32} />
                    <span className="sugerencia-texto">
                      <span className="sugerencia-principal">{principal}</span>
                      {secundario !== '' ? <span className="sugerencia-secundaria">{secundario}</span> : null}
                    </span>
                  </button>
                </li>
              )
            })}
          </ul>
        ) : null}
      </div>

      {/* Grilla de personajes */}
      {filtrados.length === 0 ? (
        <div className="centrado">
          <div>
            <IconBuscar />
            <p>{t('sin_resultados')}</p>
          </div>
        </div>
      ) : modoGrilla === ModoGrilla.TARJETAS ? (
        <GrillaTarjetas
          personajes={filtrados}
          seleccion={seleccion}
          japones={japones}
          onToggle={manejarToggle}
        />
      ) : (
        <GrillaLista
          personajes={filtrados}
          seleccion={seleccion}
          japones={japones}
          onToggle={manejarToggle}
        />
      )}

      {seleccionados > 0 ? (
        <button type="button" className="fab" aria-live="polite" onClick={() => setSheetAbierto(true)}>
          <IconCorazon />
          {t('ver_afinidad')}
        </button>
      ) : null}

      <BottomSheet open={sheetAbierto && resultado !== null} onClose={() => setSheetAbierto(false)} labelledBy="resultado-titulo">
        {resultado ? <ResultadoPanel modelo={modelo} res={resultado} japones={japones} /> : null}
      </BottomSheet>

      <Dialogo
        open={dialogoQuitar}
        titulo={t('quitar_hijo_titulo')}
        onClose={() => setDialogoQuitar(false)}
      >
        <button
          type="button"
          className="boton-texto"
          onClick={() => {
            store.confirmarQuitarSoloHijo()
            setDialogoQuitar(false)
          }}
        >
          {t('quitar_solo_hijo')}
        </button>
        <button
          type="button"
          className="boton-texto"
          onClick={() => {
            store.limpiarTodo()
            setDialogoQuitar(false)
          }}
        >
          {t('limpiar_todo')}
        </button>
      </Dialogo>
    </div>
  )
}

/* ---------- Slots coloreados por genealogía ---------- */

function SlotChip({ slot, onQuitar }: { slot: number; onQuitar: (slot: number) => void }) {
  const { modelo, seleccion } = useAppStore()
  const { t, japones } = useI18n()
  const id = seleccion[slot]
  const personaje = id !== null && modelo ? modelo.porId(id) : null
  const rolColor = colorDeGenealogia(slot)
  const borde = personaje ? `color-mix(in srgb, ${rolColor} 70%, transparent)` : 'var(--contorno-variante)'

  if (!personaje) {
    return (
      <div className="slot-chip vacio" style={{ borderColor: borde }}>
        <span className="slot-etiqueta" style={{ color: rolColor }}>
          {t(etiquetaRol(slot))}
        </span>
        <span className="slot-nombre">—</span>
      </div>
    )
  }

  return (
    <button
      type="button"
      className="slot-chip"
      style={{ borderColor: borde }}
      onClick={() => onQuitar(slot)}
      aria-label={`${t(etiquetaRol(slot))}: ${displayName(personaje, japones)}. ${t('quitar_personaje')}`}
    >
      <span className="slot-etiqueta" style={{ color: rolColor }}>
        {t(etiquetaRol(slot))}
      </span>
      <span className="slot-nombre seleccionado">{displayName(personaje, japones)}</span>
    </button>
  )
}

/* ---------- Modo TARJETAS ---------- */

function GrillaTarjetas({
  personajes,
  seleccion,
  japones,
  onToggle,
}: {
  personajes: Character[]
  seleccion: (number | null)[]
  japones: boolean
  onToggle: (id: number) => void
}) {
  return (
    <ul className="grilla-tarjetas">
      {personajes.map((c) => (
        <li key={c.charId}>
          <CardTarjeta personaje={c} seleccion={seleccion} japones={japones} onToggle={onToggle} />
        </li>
      ))}
    </ul>
  )
}

function CardTarjeta({
  personaje,
  seleccion,
  japones,
  onToggle,
}: {
  personaje: Character
  seleccion: (number | null)[]
  japones: boolean
  onToggle: (id: number) => void
}) {
  const { t } = useI18n()
  const principal = displayName(personaje, japones)
  const secundario = japones ? personaje.enName ?? '' : personaje.jpName ?? ''
  const roles = posicionesRol(seleccion, personaje.charId)
  const seleccionado = roles.length > 0
  const rolesTexto = roles.map((r) => t(rolCorto(r))).join(', ')

  return (
    <button
      type="button"
      role="checkbox"
      aria-checked={seleccionado}
      aria-describedby={rolesTexto !== '' ? `roles-${personaje.charId}` : undefined}
      className={seleccionado ? 'card-tarjeta seleccionada' : 'card-tarjeta'}
      onClick={() => onToggle(personaje.charId)}
    >
      {rolesTexto !== '' ? (
        <span id={`roles-${personaje.charId}`} className="oculto-visualmente">
          {rolesTexto}
        </span>
      ) : null}
      <span className="avatar-envoltura">
        <Avatar id={personaje.charId} nombre={principal} tamano={64} />
        {seleccionado ? (
          <span className="check" aria-hidden="true">
            ✓
          </span>
        ) : null}
      </span>
      <span className="nombre-principal">{principal}</span>
      {secundario !== '' ? <span className="nombre-secundario">{secundario}</span> : null}
      {roles.length > 0 ? (
        <span className="roles-flow">
          {roles.map((r) => (
            <span key={r} className="rol-tag">
              {t(rolCorto(r))}
            </span>
          ))}
        </span>
      ) : null}
    </button>
  )
}

/* ---------- Modo LISTA ---------- */

function GrillaLista({
  personajes,
  seleccion,
  japones,
  onToggle,
}: {
  personajes: Character[]
  seleccion: (number | null)[]
  japones: boolean
  onToggle: (id: number) => void
}) {
  return (
    <ul className="grilla-lista">
      {personajes.map((c) => (
        <li key={c.charId}>
          <CardFila personaje={c} seleccion={seleccion} japones={japones} onToggle={onToggle} />
        </li>
      ))}
    </ul>
  )
}

function CardFila({
  personaje,
  seleccion,
  japones,
  onToggle,
}: {
  personaje: Character
  seleccion: (number | null)[]
  japones: boolean
  onToggle: (id: number) => void
}) {
  const { t } = useI18n()
  const principal = displayName(personaje, japones)
  const secundario = japones ? personaje.enName ?? '' : personaje.jpName ?? ''
  const roles = posicionesRol(seleccion, personaje.charId)
  const seleccionado = roles.length > 0
  const rolesTexto = roles.map((r) => t(rolCorto(r))).join(', ')

  return (
    <button
      type="button"
      role="checkbox"
      aria-checked={seleccionado}
      aria-describedby={rolesTexto !== '' ? `roles-${personaje.charId}` : undefined}
      className={seleccionado ? 'card-fila seleccionada' : 'card-fila'}
      onClick={() => onToggle(personaje.charId)}
    >
      {rolesTexto !== '' ? (
        <span id={`roles-${personaje.charId}`} className="oculto-visualmente">
          {rolesTexto}
        </span>
      ) : null}
      <span className="franja" style={{ background: colorDeAvatar(personaje.charId) }} aria-hidden="true" />
      <Avatar id={personaje.charId} nombre={principal} tamano={48} />
      <span className="card-fila-texto">
        <span className="nombre-principal">{principal}</span>
        {secundario !== '' ? <span className="nombre-secundario">{secundario}</span> : null}
      </span>
      {seleccionado ? (
        <span className="roles-flow">
          {roles.map((r) => (
            <span key={r} className="rol-tag">
              {t(rolCorto(r))}
            </span>
          ))}
          <span className="check-texto" aria-hidden="true">
            ✓
          </span>
        </span>
      ) : null}
    </button>
  )
}
