// sitio/src/lib/components/Avatar.svelte
<script lang="ts">
/* Avatar pixel-art con fallback de iniciales + gradiente HSL. */

import { asset } from '$app/paths'
import { store } from '../state/store.svelte'
import { EstiloAvatar } from '../data/prefs'
import { gradienteDeAvatar, inicialesDe } from '../theme/theme'

const CARPETA: Record<EstiloAvatar, string> = {
  [EstiloAvatar.COLOR]: 'color',
  [EstiloAvatar.GRISES]: 'bw5',
  [EstiloAvatar.MONOCROMO]: 'bw1',
}

interface Props {
  id: number
  nombre: string
  tamano?: number
  class?: string
}

let { id, nombre, tamano = 40, class: clase = '' }: Props = $props()

const url = $derived(asset(`/avatars/${CARPETA[store.estiloAvatar]}/${id}.png`))
let urlConError = $state<string | null>(null)
const fallo = $derived(urlConError === url)
</script>

{#if fallo}
  <span
    aria-hidden="true"
    class={clase}
    style="width:{tamano}px;height:{tamano}px;border-radius:50%;flex-shrink:0;background:{gradienteDeAvatar(
      id,
    )};display:inline-flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:{Math.max(
      10,
      Math.round(tamano * 0.3),
    )}px"
  >
    {inicialesDe(nombre)}
  </span>
{:else}
  <img
    src={url}
    alt=""
    aria-hidden="true"
    class={clase}
    style="width:{tamano}px;height:{tamano}px;border-radius:50%;flex-shrink:0;object-fit:cover"
    onerror={() => (urlConError = url)}
    loading="lazy"
  />
{/if}

// web/src/components/Avatar.tsx
/* Avatar pixel-art con fallback de iniciales + gradiente HSL.
   Espejo de ui/componentes/Componentes.kt (Avatar) y AvatarResources.kt. */

import { useState } from 'react'
import { useAppStore } from '../state/store'
import { EstiloAvatar } from '../data/prefs'
import { gradienteDeAvatar, inicialesDe } from '../theme/theme'

const CARPETA: Record<EstiloAvatar, string> = {
  [EstiloAvatar.COLOR]: 'color',
  [EstiloAvatar.GRISES]: 'bw5',
  [EstiloAvatar.MONOCROMO]: 'bw1',
}

function avatarUrl(charId: number, estilo: EstiloAvatar): string {
  return `${import.meta.env.BASE_URL}avatars/${CARPETA[estilo]}/${charId}.png`
}

interface AvatarProps {
  id: number
  nombre: string
  tamano?: number
  className?: string
}

export function Avatar({ id, nombre, tamano = 40, className }: AvatarProps) {
  const { estiloAvatar } = useAppStore()
  const [error, setError] = useState(false)

  const estilo: React.CSSProperties = {
    width: tamano,
    height: tamano,
    borderRadius: '50%',
    flexShrink: 0,
  }

  if (error) {
    return (
      <span
        aria-hidden="true"
        className={className}
        style={{
          ...estilo,
          background: gradienteDeAvatar(id),
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: '#fff',
          fontWeight: 700,
          fontSize: Math.max(10, Math.round(tamano * 0.3)),
        }}
      >
        {inicialesDe(nombre)}
      </span>
    )
  }

  return (
    <img
      src={avatarUrl(id, estiloAvatar)}
      alt=""
      aria-hidden="true"
      className={className}
      style={{ ...estilo, objectFit: 'cover' }}
      onError={() => setError(true)}
      loading="lazy"
    />
  )
}
